# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0003_foodtypes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtypes',
            table='axf_foodtypes',
        ),
    ]
