# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0004_auto_20181105_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtypes',
            old_name='childtypename',
            new_name='childtypenams',
        ),
    ]
