# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0005_auto_20181105_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtypes',
            old_name='childtypenams',
            new_name='childtypenames',
        ),
    ]
