# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0006_auto_20181105_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20)),
                ('productimg', models.CharField(max_length=255)),
                ('productname', models.CharField(max_length=30)),
                ('productlongname', models.CharField(max_length=90)),
                ('isxf', models.BooleanField(default=0)),
                ('pmdesc', models.IntegerField()),
                ('specifics', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoryid', models.IntegerField()),
                ('childcid', models.IntegerField()),
                ('childcidname', models.CharField(max_length=30)),
                ('dealerid', models.CharField(max_length=30)),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('productnum', models.IntegerField(verbose_name='销量')),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
