# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productlongname',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=130),
        ),
    ]
